### ISSUE TITLE
Error running "docker-compose up" to setup alma_inventory_docker

### ISSUE THREAD

**Issue by beau1smith** [dlingley/alma_inventory_docker#1]
I'm following the instructions. When I get to the step where I'm supposed to run "docker-compose up in the project directory, I get this error:

sudo docker-compose up
Building app
Step 1/6 : FROM php:5.6.36-apache
 ---> e683056c8c8d
Step 2/6 : MAINTAINER Dean Lingley
 ---> Using cache
 ---> 1cdb6d21d67c
Step 3/6 : COPY . /srv/app
 ---> Using cache
 ---> e94e844f8fd4
Step 4/6 : COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf
 ---> Using cache
 ---> feb13effc264
Step 5/6 : RUN chown -R www-data:www-data /srv/app     && a2enmod rewrite
 ---> Using cache
 ---> 0cfd5e75608b
Step 6/6 : RUN chmod a+rwx -R /srv/app/cache
 ---> Running in cb72b1722900
chmod: cannot access '/srv/app/cache': No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c chmod a+rwx -R /srv/app/cache' returned a non-zero code: 1

**Comment by dlingley** [comment]
Should be fixed now... Needed blank cache folders.
